name: Deploy to AWS S3

on:
  push:
    branches:
      - main  # 或者您的主分支名称

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # 您的AWS区域

      - name: Deploy to S3
        run: |
          aws s3 sync . s3://chongweiban --delete --exclude ".git/*" --exclude ".github/*"
          
      - name: Invalidate CloudFront (如果您使用CloudFront)
        run: |
          # 如果您有CloudFront，取消下面注释并添加您的分配ID
          # aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*" 